exports.Config={
    Specailty:[
        {id:1,name:"全栈"},
        {id:2,name:"UI/UE"},
        {id:3,name:"JavaEE/大数据"},
        {id:4,name:"Python"},
        {id:5,name:"软件测试"}
    ],
    StudentSrc:[
        {id:1,name:"网络"},
        {id:2,name:"社招"},
        {id:3,name:"校招"},
        {id:4,name:"转介绍"}
    ],
    EduDegree:[
        {id:1,name:"大学"},
        {id:2,name:"大专"},
        {id:3,name:"高中"},
        {id:4,name:"中专"},
        {id:5,name:"初中"},
    ],
    FeeRule:[
        {id:1,month:6,tuition:19800,dormitory_rent:3600,dormitory_deposit:600,dormiroty_mng:300,pc_deposit:1700,pc_usage:720,pc_buy:1700,cloth:0,total:26720},
        {id:2,month:10,tuition:29800,dormitory_rent:6000,dormitory_deposit:600,dormiroty_mng:700,pc_deposit:1700,pc_usage:1200,pc_buy:1700,cloth:148,total:40148},
        {id:3,month:30,tuition:49800,dormitory_rent:18000,dormitory_deposit:600,dormiroty_mng:1000,pc_deposit:1700,pc_usage:3600,pc_buy:1700,cloth:148,total:64848},
    ],
    FeeType:[
        {id:0,name:"学杂费"},
        {id:1,name:"学费"},
        {id:2,name:"住宿费"},
        {id:3,name:"住宿押金"},
        {id:4,name:"住宿管理费"},
        {id:5,name:"笔记本押金"},
        {id:6,name:"笔记本租金"},
        {id:7,name:"笔记本购买"},
        {id:8,name:"校服费"},
        {id:9,name:"被褥费"},
        {id:10,name:"学历费"},
        {id:11,name:"入学路费"},//???
        {id:12,name:"入学住宿费"},//？？？
    ],
    PayType:[
        {id:1,name:"全款"},
        {id:2,name:"现金分期"},
        {id:3,name:"贷款"},
    ],
    EnrollerLevel:[
        {id:0,name:"总监"},
        {id:1,name:"区域经理"},
        {id:2,name:"县办"},
    ],
    //招生老师代理费的状态
    EnrollerFeeState:[
        {id:0,name:"学费未交清"},
        {id:1,name:"学费已交清，待审核"},
        {id:2,name:"学费已交清，待支付"},
        {id:3,name:"学费已交清，已支付"},
        {id:4,name:"学生退学，待退还"},
        {id:5,name:"学生退学，已退还"},
    ],
    TuitionType:[
        {id:0,name:"贷款"},
        {id:1,name:"全款"},
        {id:2,name:"分期"},
    ]
}
exports.Enroller_Rebates=[0.25,0.05,0.04];//返点